version: "3"
services:
  lune-server:
    container_name: lune-server
    build:
      dockerfile: server/Dockerfile
      args:
        - LUNE_VERSION=0.7.11
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/server
    develop:
      watch:
        - action: sync+restart
          path: ./server
