version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      args:
        - LUNE_VERSION=0.8.2
    environment:
      LOG_LEVEL: debug
    ports:
      - "8080:8080"

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui:v5.11.2
    environment:
      URL: http://localhost:8080/openapi.yml
    ports:
      - "8081:8080"
