version: "3"
services:
  lune-server:
    container_name: lune-server
    build:
      dockerfile: server/Dockerfile
      args:
        - LUNE_VERSION=0.7.11
    environment:
      LOG_LEVEL: debug
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/server
    command: ["lune", "run", "server/server.luau"]

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui:v5.11.2
    ports:
      - "8081:8080"
