version: "3"
services:
  swatch-api:
    container_name: swatch-api
    build: ./server
    environment:
      LOG_LEVEL: debug
    ports:
      - "8080:8080"

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui:v5.11.2
    ports:
      - "8081:8080"
