[tools]
darklua = { source = "seaofvoices/darklua", version = "0.12.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.32.0" }
lune = { source = "lune-org/lune", version = "0.8.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "kampfkarren/selene", version = "0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.17.1" }
tarmac = { source = "Roblox/tarmac", version = "0.7.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.2.1" }
