openapi: 3.1.0

info:
  title: Title
  description: Description
  version: 1.0.0
  basePath: /v1

components:
  schemas:
    SummaryAndDescription:
      summary: "A short summary"
      description: "A long-form description of the schema"

    SummaryOnly:
      summary: "A short summary"

    DescriptionOnly:
      description: "A long-form description of the schema"

    Empty:
      foo: true
