openapi: 3.1.0

info:
  title: Swatch
  description: |
    The Swatch API is used by the Swatch plugin for Roblox Studio for querying
    Microsoft's Visual Studio Marketplace for information about themes and
    processing those themes into something Roblox Studio can consume.
  version: 1.0.0
  basePath: /v1

servers:
  - url: https://swatch.vocksel.com/v1

paths:
  /extensions:
    parameters:
      - name: pageSize
        description: Size of the page
        in: query
        schema:
          type: integer
      - name: page
        description: Current page
        in: query
        schema:
          type: integer
    get:
      summary: "Returns a list of extensions from the VS Marketplace"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Extension"
        "500":
          description: "Something went wrong when communicating with VS Marketplace API"

  /themes/{extensionId}/{extensionVersion}:
    parameters:
      - in: extensionId
        name: pageSize
        required: true
        format: "string"
        schema:
          type: integer
        description: Size of the page
      - in: path
        name: extensionVersion
        required: true
        format: "string"
        schema:
          type: integer
        description: Current page
    get:
      summary: "Returns the theme definition(s) of the given VSCode extension"
      responses:
        "200":
          type: array
          items:
            $ref: "#/components/schemas/Theme"
        "400":
          description: "One or more of the query parameters were incorrect"
        "500":
          description: "One or more of the query parameters were incorrect"

components:
  schemas:
    Extension:
      summary: "Extension from the VS Marketplace"
      type: object
      properties:
        extensionId:
          type: string
        name:
          type: string
        latestVersion:
          type: string
        publisher:
          type: string
        # themes:
        #   type: array
        #   items:
        #     $ref: "#/components/schemas/Theme"
      example:

    Theme:
      summary: "Mapping of Roblox Studio-compatible color names to VSCode theme colors"
      type: object
      properties:

