name: CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  DOCKERHUB_USERNAME: vocksel
  DOCKERHUB_REPO: swatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}

      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./server
          build-args: |
            LUNE_VERSION=0.8.6
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
