name: Release

on:
  pull_request:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: just init
      - run: just build-here prod

      - uses: softprops/action-gh-release@v1
        if: ${{ github.event.release }}
        with:
          files: |
            *.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
